# src/models/config.yaml

# Configuration for MOCLIP model
# Any changes to this config are not supported in the implementation. 

variant: 'basic'
geometry_backbone: 'resnet_custom'
spectra_backbone: 'spectra_mlp'

geometry_backbone_params:
  output_features: 64
  backbone: resnet18    # for ResNetCustom

spectra_backbone_params:
  output_features: 64
  input_features: 58  

# initial temperature 
init_temperature: 0.07

#Weights path
weights_path: '../src/models/weights/moclip_v2.pth'
